### ISSUE TITLE
Extension is broken

### ISSUE THREAD

**Issue by kieranlittle667** [minorninth/accessible-wordle#4]
Hi,
From what I can tell wordle have slightly redesigned the website (the keyboard looks bigger) meaning that the extention is now broken and does not work at all. I'm playing on iOS but have heard it's broken for other platforms also.

**Comment by devbanana** [comment]
Can confirm. Also broken for me.

**Comment by DHSDarcy** [comment]
Can confirm.  It's broken on both macOS and iPadOs.

**Comment by minorninth** [comment]
Hey, thanks for writing and glad you've all been enjoying it! Yep, it's not
just you - it looks like they totally rewrote the whole
Wordle implementation on the New York Times site so the extension and
bookmarklet broke. I can definitely fix it but it will take some time, I'll
let you know.
- Dominic

**Comment by minorninth** [comment]
Update: the bookmarklet has been updated and should work now. The Chrome
extension is also ready but the update hasn't been published yet, stay
tuned!

**Comment by dparker21** [comment]
Hi Dominic, thanks for all your work on this. The bookmarklet is still not working for me after deleting the old one, copying fresh code from the Accessible Wordle page, and creating a new bookmarklet. I'm not sure what else to try at this point. I'm using iOS Safari. It would really be nice if NYT just implemented the accessible interface into the full game...

Thanks again,
Daniel

**Comment by devbanana** [comment]
I can confirm the new bookmarklet does work for me on Safari.

**Comment by dparker21** [comment]
It's still not working for me, but other people have also said it works for them. I wonder if it's because I already opened up non-accessible Wordle today and tried to guess a word. Does that prevent the bookmarklet from running until Wordle refreshes itself at midnight?

**Comment by dparker21** [comment]
Ok, I got it to work. To do this I deleted both my Wordle bookmark and the accessible bookmarklet, then cleared Safari history and website data, reinstalled both bookmarks, cleared history and data again, opened Wordle and then the bookmarklet.

Thanks again to all for your help.

**Comment by kieranlittle667** [comment]
Have you completely recreated your bookmark? I had to do this and refreshed a few times and eventually it worked.
